name: madsci_example_event_manager
services:
  mongodb:
    container_name: mongodb
    image: mongo:8.0
    ports:
      - 27017:27017
  data_manager:
    container_name: data_manager
    image: ghcr.io/ad-sdl/madsci:latest
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
    network_mode: host
    volumes:
      - /path/to/your/managers/directory:/home/madsci/managers/
      - .madsci:/home/madsci/.madsci/
    command: python -m madsci.data_manager.data_server --definition /home/madsci/managers/example_data.manager.yaml
    depends_on:
      - mongodb
  minio:
    container_name: minio
    image: minio/minio
    restart: unless-stopped
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ~/minio/data:/data
    command: server /data --console-address ":9001"
