name: madsci_example_lab
services:
  mongodb:
    container_name: mongodb
    image: mongo:8.0
    ports:
      - 27017:27017
  redis:
    container_name: redis
    image: redis:7.4
    ports:
      - 6379:6379
  postgres:
    container_name: postgres
    image: postgres:17
    environment:
      - POSTGRES_USER=rpl
      - POSTGRES_PASSWORD=rpl
      - POSTGRES_DB=resources
    ports:
      - 5432:5432

  #Managers

  lab_manager:
    container_name: lab_manager
    image: ghcr.io/ad-sdl/madsci_dashboard:latest
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
    network_mode: host
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-./}:/home/madsci/example_lab
      - ${LOCAL_WORKSPACE_FOLDER:-./}.madsci:/home/madsci/.madsci/
      - ${LOCAL_WORKSPACE_FOLDER:-./}/../src/madsci_squid/ui:/home/madsci/ui
    command: python -m madsci.squid.lab_server --definition /home/madsci/example_lab/example_lab.lab.yaml
    restart: on-failure
    depends_on:
      - redis
      - event_manager
  event_manager:
    container_name: event_manager
    image: ghcr.io/ad-sdl/madsci:latest
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      - USER_ID=1000
      - GROUP_ID=100
    network_mode: host
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-../}/example_lab:/home/madsci/example_lab/
      - ${LOCAL_WORKSPACE_FOLDER:-../}/.madsci:/home/madsci/.madsci/
    command: python -m madsci.event_manager.event_server
    depends_on:
      - mongodb
  experiment_manager:
    container_name: experiment_manager
    image: ghcr.io/ad-sdl/madsci:latest
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      - USER_ID=1000
      - GROUP_ID=100
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-../}/example_lab:/home/madsci/example_lab/
      - ${LOCAL_WORKSPACE_FOLDER:-../}/.madsci:/home/madsci/.madsci/
    command: python -m madsci.experiment_manager.experiment_server
    network_mode: host
    depends_on:
      - mongodb
  resource_manager:
    container_name: resource_manager
    image: ghcr.io/ad-sdl/madsci:latest
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-../}/example_lab:/home/madsci/example_lab/
      - ${LOCAL_WORKSPACE_FOLDER:-../}/.madsci:/home/madsci/.madsci/
    command: python -m madsci.resource_manager.resource_server
    network_mode: host
    depends_on:
      - postgres
  data_manager:
    container_name: data_manager
    image: ghcr.io/ad-sdl/madsci:latest
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-../}/example_lab:/home/madsci/example_lab/
      - ${LOCAL_WORKSPACE_FOLDER:-../}/.madsci:/home/madsci/.madsci/
    command: python -m madsci.data_manager.data_server
    network_mode: host
    depends_on:
      - mongodb
  workcell_manager:
    container_name: workcell_manager
    image: ghcr.io/ad-sdl/madsci:latest
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      - USER_ID=1000
      - GROUP_ID=100
    network_mode: host
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-../}/example_lab:/home/madsci/example_lab/
      - ${LOCAL_WORKSPACE_FOLDER:-../}/.madsci:/home/madsci/.madsci/
      - ${LOCAL_WORKSPACE_FOLDER:-../}/src/madsci_workcell_manager/ui:/home/madsci/ui
    command: python -m madsci.workcell_manager.workcell_server --cold_start_delay 0
    restart: on-failure
    depends_on:
      - redis
      - resource_manager
      - postgres
   #Nodes
  liquidhandler:
    container_name: liquidhandler
    image: ghcr.io/ad-sdl/madsci:latest
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-../}/example_lab:/home/madsci/example_lab/
      - ${LOCAL_WORKSPACE_FOLDER:-../}/.madsci:/home/madsci/.madsci/
    command: python example_lab/example_modules/liquidhandler.py --definition example_lab/example_modules/nodes/liquidhandler_1.node.yaml
    network_mode: host
    depends_on:
      - event_manager
  robotarm:
    container_name: robotarm
    image: ghcr.io/ad-sdl/madsci:latest
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-../}/example_lab:/home/madsci/example_lab/
      - ${LOCAL_WORKSPACE_FOLDER:-../}/.madsci:/home/madsci/.madsci/
    command: python example_lab/example_modules/robotarm.py --definition example_lab/example_modules/nodes/robotarm_1.node.yaml
    network_mode: host
    depends_on:
      - event_manager

  platereader:
    container_name: platereader
    image: ghcr.io/ad-sdl/madsci:latest
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-../}/example_lab:/home/madsci/example_lab/
      - ${LOCAL_WORKSPACE_FOLDER:-../}/.madsci:/home/madsci/.madsci/
    command: python example_lab/example_modules/platereader.py --definition example_lab/example_modules/nodes/platereader_1.node.yaml
    network_mode: host
    depends_on:
      - event_manager
