name: madsci_example_event_manager
services:
  mongodb:
    container_name: mongodb
    image: mongo:8.0
    ports:
      - 27017:27017
  event_manager:
    container_name: event_manager
    image: ghcr.io/ad-sdl/madsci:latest
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
    network_mode: host
    volumes:
      - /path/to/your/managers/directory:/home/madsci/managers/
      - .madsci:/home/madsci/.madsci/
    command: python -m madsci.event_manager.event_server --definition /home/madsci/managers/example_event.manager.yaml
    depends_on:
      - mongodb
